#!/bin/bash

if [ -e dospt ]; then
    ./dospt

    if [ $? -ne 0 ]; then
        echo "error"
        exit 1
    fi
fi

if [ -e Dockerfile ]; then
    sudo docker build -t fimage .
fi

res=$(sudo docker images | grep fimage)

if [ -n "$res" ]; then
    sudo docker run -it --name udock fimage
else
    echo "Docker image 'fimage' not found."
    exit 1
fi

